### PR TITLE
Add setup instructions to README.md

### PR DESCRIPTION
**Pull request by mfeyg**
Issue #388

### CODE REVIEW

**Comment by kyaroch** [comment]
A couple of comments:
* This is written on the assumption that you're using system Ruby. Actually, it's a good idea to use RVM or rbenv. (Installation instructions for RVM are (here)[https://rvm.io/rvm/install]. I strongly recommend doing a single-user install.)

* #4 may not be necessary as a separate step – just running `bundle install` worked for me once I had Postgres installed. We can suggest trying it if that doesn't work.

**Comment by mfeyg** [comment]
Those two comments might be related. Using system Ruby, the `pg` gem wouldn't install for me without that architecture flag for some reason. I could look into setting it up with rbenv and documenting that process tomorrow.

**Comment by mfeyg** [comment]
I've changed the instructions to use rbenv. If this gets accepted I'll open an issue to add a `.ruby-version` file. 2.2.2 works for me, but I can't find a version specified anywhere.

**Comment by dgliwa** [comment]
Just a comment on this, we address this issue in #397, which should make setup as easy as typing a few commands.

**Pull request merged**
